# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import pyqtgraph as pg
from random import uniform

class Ui_Form(object):
    def __init__(self):
        self.time = [x for x in range(10)]
        self.voltage = [uniform(11, 14) for _ in range(10)]
        self.counter = len(self.time)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 342)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 441, 291))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.widget1 = PlotWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout.addWidget(self.splitter, 0, 0, 2, 1)

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.update)
        self.timer.start()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Batteriespannung"))
        self.widget1.plot(self.time, self.voltage)

        pen = pg.mkPen(color=(255, 0, 0))
        self.data_line = self.widget1.plot(self.time, self.voltage, pen=pen)



    def update(self):
            self.time = self.time + [self.counter]
            self.voltage = self.voltage + [uniform(11, 14)]
            self.data_line.setData(self.time, self.voltage)
            self.lcdNumber.display(str(round(self.voltage[-1],2)))
            self.counter += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
