# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lFitrstname = QtWidgets.QLabel(self.page)
        self.lFitrstname.setObjectName("lFitrstname")
        self.verticalLayout_3.addWidget(self.lFitrstname)
        self.InFirstname = QtWidgets.QLineEdit(self.page)
        self.InFirstname.setObjectName("InFirstname")
        self.verticalLayout_3.addWidget(self.InFirstname)
        self.lLastname = QtWidgets.QLabel(self.page)
        self.lLastname.setObjectName("lLastname")
        self.verticalLayout_3.addWidget(self.lLastname)
        self.InLastname = QtWidgets.QLineEdit(self.page)
        self.InLastname.setObjectName("InLastname")
        self.verticalLayout_3.addWidget(self.InLastname)
        self.lWarn = QtWidgets.QLabel(self.page)
        self.lWarn.setText("")
        self.lWarn.setObjectName("lWarn")
        self.verticalLayout_3.addWidget(self.lWarn)
        self.btenter = QtWidgets.QPushButton(self.page)
        self.btenter.setObjectName("btenter")
        self.verticalLayout_3.addWidget(self.btenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lOut = QtWidgets.QLabel(self.page_2)
        self.lOut.setAlignment(QtCore.Qt.AlignCenter)
        self.lOut.setObjectName("lOut")
        self.verticalLayout_2.addWidget(self.lOut)
        self.back = QtWidgets.QPushButton(self.page_2)
        self.back.setObjectName("back")
        self.verticalLayout_2.addWidget(self.back)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lFitrstname.setText(_translate("MainWindow", "firstname"))
        self.lLastname.setText(_translate("MainWindow", "lastname"))
        self.btenter.setText(_translate("MainWindow", "enter"))
        self.lOut.setText(_translate("MainWindow", "firstname: __ lastname:___"))
        self.back.setText(_translate("MainWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
